apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow-base
type: Opaque
data:
  AIRFLOW__CORE__FERNET_KEY: ZmVybmV0LWtleQ==  # Chave Fernet base64
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: YXdzX2RlZmF1bHQ=  # aws_default em base64
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: czM6Ly9haXJmbG93LWxvZ3Mv  # s3://airflow-logs em base64
