apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow-homolog
spec:
  selector:
    app: airflow-webserver  # Deve corresponder às labels dos pods
  ports:
    - protocol: TCP
      port: 8000            # Porta do serviço
      targetPort: 8080      # Porta do contêiner no pod
  type: ClusterIP           # Pode mudar para NodePort ou LoadBalancer conforme necessário
