resources:
  - pvc-dags.yml
  - pvc-logs.yml
  - deployment-patch.yml
  - airflow-secrets.yml

patches:
  - path: deployment-patch.yml

configMapGenerator:
  - name: airflow-config
    files:
      - airflow-values.yml
