apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-homolog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://seu-repositorio.git'
    targetRevision: main
    path: airflow/homolog
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow-homolog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true